export const PLAY_INTERVAL = 500;
export const END_OF_NUMBER_FREQUENCY = 20_600;
export const START_OF_SEQUENCE_FREQUENCY = 20_700;
export const END_OF_SEQUENCE_FREQUENCY = 20_800;

export const ERROR_DETECTED_FREQUENCY = 20_900;
export const NO_ERROR_FREQUENCY = 21_000;

export const NUMBERS_TOP_FREQUENCY = 20_500;
export const NUMBERS_BOTTOM_FREQUENCY = 19_000;
export const TOTAL_BITS = 15;

export const CARRIER_FREQUENCY = 18_800;
export const SAMPLE_RATE = 48_000;

export const MIN_FREQ = 18_600;
export const MAX_FREQ = 21_200;

export const FREQUENCY_GAP =
  (NUMBERS_TOP_FREQUENCY - NUMBERS_BOTTOM_FREQUENCY) / TOTAL_BITS;
