export const PLAY_INTERVAL = 200;

export const TOTAL_BITS = 16;

// CHANNEL BANDWIDTH START
export const CARRIER_BASE_FREQUENCY = 18_800;

export const SILENT_BASE_FREQUENCY = 18_850;

export const SIGOKY_BASE_FREQUENCY = 18_950;
export const SIGERR_BASE_FREQUENCY = 19_000;

export const BIT_ZERO_BASE_FREQUENCY = 19_050;
export const BIT_ONE_BASE_FREQUENCY = 19_100;

export const END_OF_NUMBER_BASE_FREQUENCY = 19_150;
export const START_OF_SEQUENCE_BASE_FREQUENCY = 19_200;
export const END_OF_SEQUENCE_BASE_FREQUENCY = 19_250;

export const TOP_BASE_FREQUENCY = 19_250;
// CHANNEL BANDWIDTH END

export const SAMPLE_RATE = 48_000;

export const MIN_VALID_DATA_FREQ = 18_500;
export const MAX_VALID_DATA_FREQ = 21_500;

export const CHANNEL_BANDWIDTH = 500;
export const FREQUENCY_ROUND_GAP = 50;
